CREATE OR REPLACE PROCEDURE SP_CREATEINJURESLINK(
    P_INJURYSUSPENSIONID IN NUMBER,
    P_SEVERITY IN NUMBER
) AS
BEGIN
    INSERT INTO INJURESLINK (
        INJURYSUSPENSIONID,
        SEVERITY
    ) VALUES (
        P_INJURYSUSPENSIONID,
        P_SEVERITY
    );
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE SP_UPDATEINJURESLINK( P_INJURESLINKID IN NUMBER, P_INJURYSUSPENSIONID IN NUMBER, P_SEVERITY IN NUMBER ) AS
BEGIN
    UPDATE INJURESLINK
    SET
        INJURYSUSPENSIONID = P_INJURYSUSPENSIONID,
        SEVERITY = P_SEVERITY
    WHERE
        INJURESLINKID = P_INJURESLINKID;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_DELETEINJURESLINK(
    P_INJURESLINKID IN NUMBER
) AS
BEGIN
    DELETE FROM INJURESLINK
    WHERE
        INJURESLINKID = P_INJURESLINKID;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_GETALLINJURESLINK(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            *
        FROM
            INJURESLINK;
END;
/

CREATE OR REPLACE PROCEDURE SP_GETINJURESLINKBYID(
    P_INJURESLINKID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            *
        FROM
            INJURESLINK
        WHERE
            INJURESLINKID = P_INJURESLINKID;
END;
/